[project]
name = "snakemake-report-plugin-nanopub"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.12,<4"
ruff = ">=0.10.0,<0.11"
pytest = ">=8.3.5,<9"
pytest-cov = ">=6.0.0,<7"
rdflib = ">=7.0.0"

[pypi-dependencies]
nanopub = ">=2.2.0"
snakemake = ">=8.0.0"
snakemake-interface-common = ">=1.17.4,<2.0.0"
snakemake-interface-report-plugins = ">=1.1.0,<2.0.0"
snakemake-report-plugin-nanopub = { path = ".", editable = true }

[tasks]
format = "ruff format"
lint = "ruff check"
qc = { depends-on = ["format", "lint"] }
test = "pytest"
coverage-report = "pytest --cov=src/snakemake_report_plugin_nanopub --cov=snakemake_report_plugin_nanopub_graph --cov-report=term-missing --cov-report=html"

[system-requirements]
linux = "4.18"
